language: csharp
solution: Projbook.sln
install:
  - nuget restore Projbook.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Projbook.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Projbook.Tests/bin/Release/Projbook.Tests.dll
  - bash ./post-build.sh
deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
  on:
    tags: true